### obtener todos los vehículos
GET http://localhost:3000/api/vehiculo

### obtener un vehículo por patente
GET http://localhost:3000/api/vehiculo/ABC123

### crear un vehículo
POST http://localhost:3000/api/vehiculo
Content-Type: application/json

{
    "patente": "ABC123",
    "modelo": "Toyota Hilux",
    "tipoVehiculo": 1,
    "client":1
    
}

### actualizar un vehículo  
PUT http://localhost:3000/api/vehiculo/ABC123
Content-Type: application/json

{
    "modelo":"yamaha2000"
}

### eliminar un vehículo
DELETE http://localhost:3000/api/vehiculo/ABC123