GET http://localhost:3000/api/sucursal

### obtener un sucursalistrador por id
GET http://localhost:3000/api/sucursal/1

### crear un sucursalistrador
POST http://localhost:3000/api/sucursal
Content-Type: application/json

{
    "direction": "Catamarca 3233",
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSatYcz_yvWRoTHqhQr8JVN0FH-H4aoYmFVw&s",
    "admin": 1,
    "razonSocial": "Cochera Centro"
} 

### actualizar un sucursalistrador
PUT http://localhost:3000/api/sucursal/3
Content-Type: application/json

{
    "complete_name": "Ayrton Senna",
    "email": "senna.sucursal@example.com",
    "password": "NewsucursalPassword456"
}

### eliminar un sucursalistrador
DELETE http://localhost:3000/api/sucursal/1