GET http://localhost:3000/api/sucursal

### obtener una sucursal por id
GET http://localhost:3000/api/sucursal/1

### crear un sucursal
POST http://localhost:3000/api/sucursal
Content-Type: application/json

{
    "direction": "Catamarca 3233",
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSatYcz_yvWRoTHqhQr8JVN0FH-H4aoYmFVw&s",
    "admin": 1,
    "razonSocial": "Cochera Centro"
} 

### actualizar un sucursal
PUT http://localhost:3000/api/sucursal/1
Content-Type: application/json

{
    "razonSocial": "Cochera sur Pachi"
}

### eliminar un sucursal
DELETE http://localhost:3000/api/sucursal/2