### obtener todos los tipos de servicio
GET http://localhost:3000/api/cochera?state=disponible&admin=1

### obtener un tipo de servicio por id
GET http://localhost:3000/api/cochera/9

### crear un tipo de servicio
POST http://localhost:3000/api/cochera
Content-Type: application/json

{
    "number": 1,
    "tipoVehiculo": 1,
    "state": "disponible",
    "admin": 1,
    "sucursal":2
}

### actualizar un tipo de servicio
PUT http://localhost:3000/api/cochera/9
Content-Type: application/json

{
    "state": "disponible"
}

### eliminar un tipo de servicio
DELETE http://localhost:3000/api/cochera/9