### obtener todos los tipos de servicio
GET http://localhost:3000/api/cochera?state=disponible

### obtener un tipo de servicio por id
GET http://localhost:3000/api/cochera/9

### crear un tipo de servicio
POST http://localhost:3000/api/cochera
Content-Type: application/json

{
    "number": 12,
    "tipoVehiculo": 1,
    "state": "disponible",
    "admin": 1,
    "sucursal":1
}

### actualizar un tipo de servicio
PUT http://localhost:3000/api/cochera/8
Content-Type: application/json

{
    "number": "9999",
    "state": "ocupado"
}

### eliminar un tipo de servicio
DELETE http://localhost:3000/api/cochera/12a