### obtener todos los tipos de servicio
GET http://localhost:3000/api/cochera

### obtener un tipo de servicio por id
GET http://localhost:3000/api/cochera/12a

### crear un tipo de servicio
POST http://localhost:3000/api/cochera
Content-Type: application/json

{
    "numero": "8",
    "estado": "disponible",
    "tipoVehiculo": 1
}

### actualizar un tipo de servicio
PUT http://localhost:3000/api/cochera/12a
Content-Type: application/json

{
    "numero": "9999",
    "estado": "ocupado"
}

### eliminar un tipo de servicio
DELETE http://localhost:3000/api/cochera/12a