### obtener todos los tipos de servicio
GET http://localhost:3000/api/tipoServicio?admin=1

### obtener un tipo de servicio por id
GET http://localhost:3000/api/tipoServicio
### crear un tipo de servicio
POST http://localhost:3000/api/tipoServicio 
Content-Type: application/json

{
    "nombre": "Mensual",
    "precioCuota": 700,
    "cantCuotas": 1,
    "admin":1
}

### actualizar un tipo de servicio
PUT http://localhost:3000/api/tipoServicio/6
Content-Type: application/json

{
    "nombre": "trimestral",
    "precioCuota": 950,
    "cantCuotas": 3
}

### eliminar un tipo de servicio
DELETE http://localhost:3000/api/tipoServicio/8