### obtener todos los tipos de servicio
GET http://localhost:3000/api/tipoServicio

### obtener un tipo de servicio por id
GET http://localhost:3000/api/tipoServicio/1

### crear un tipo de servicio
POST http://localhost:3000/api/tipoServicio 
Content-Type: application/json

{
    "nombre": "mensual",
    "precioCuota": 25000,
    "cantCuotas": 1
}

### actualizar un tipo de servicio
PUT http://localhost:3000/api/tipoServicio/1
Content-Type: application/json

{
    "nombre": "Anual",
    "precio": 105000
}

### eliminar un tipo de servicio
DELETE http://localhost:3000/api/tipoServicio/2